import type { Metadata } from "next";
import "./globals.css";
import { Inter } from 'next/font/google'
import { Toaster } from "@/shared/components/ui/toaster";

const inter = Inter({ subsets: ['latin'], weight: ["300", "600", "400", "500", "600", "700"]})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${inter.className} antialiased`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
